website/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify, session, json, current_app
from flask_login import login_required, current_user
from flask_socketio import join_room, leave_room, emit
from datetime import datetime, timedelta
from .functions import create_room, get_rooms_count, get_public_rooms, invite_code, calculate_age, upload_to_imgbb, is_valid_image, smiley_list, add_admins, get_admins, remove_admin, handle_command
from .models import Room, User, Message
from . import db, socketio
from better_profanity import profanity
import requests, bleach, os, time
from werkzeug.utils import secure_filename

views = Blueprint('views', __name__)
MAX_IMAGE_SIZE_MB = 10

# Enable HSTS for all routes
@views.after_request
def add_hsts_header(response):
    response.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains; preload'
    return response

@socketio.on('join_room')
def handle_join_room(data):
    room_id = data['room_id']
    user = current_user.id
    name = current_user.nickname
    join_room(room_id)
    print(f'Client {user} | {name} joined room: {room_id}')

@socketio.on('leave_room')
def handle_leave_room(data):
    room_id = data['room_id']
    leave_room(room_id)
    print(f'Client left room: {room_id}')

@socketio.on("new_message")
def handle_new_message(data):
    if current_user.is_authenticated:
        room_id = data['room_id']
        user = current_user
        message = data['message']
        message = bleach.clean(message, tags=['img', 'strong', 'em', 'u', 'b', 'mark', 'del', 'sub', 'sup'], attributes=['src', 'alt'])
        message = profanity.censor(message)
        name = current_user.nickname
        recipient_id = data.get('recipient_id')  # Add this line to get the recipient id from the client
        if message.startswith("/"):
            room = Room.query.get(room_id)  # Fetch the room object
            response_message = handle_command(message, room)
            img = "https://cdn.pixabay.com/photo/2018/11/13/21/43/avatar-3814049_1280.png"
            emit('message', {'msg': response_message, 'user': 'System', 'id': user.id, 'time_sent': "System", 'img': img}, room=room_id)
        elif recipient_id:
            # Handle private messages
            db_private_message = PrivateMessage(data=message, sender_id=user.id, recipient_id=recipient_id)
            db.session.add(db_private_message)
            db.session.commit()
        else:
            # Handle regular chat messages
            db_message = Message(data=message, user_id=user.id, room_id=room_id)
            # Add the message to the database
            db.session.add(db_message)
            db.session.commit()
            print(f"New message from {name} in room {room_id}: {str(message).encode('utf-8')}")
            time_sent = str(db_message.timestamp.strftime("%H:%M"))  # Format the timestamp nicely
            if not current_user.img:
                img = "https://cdn.pixabay.com/photo/2018/11/13/21/43/avatar-3814049_1280.png"
            else:
                img = current_user.img
            emit('message', {'msg': message, 'user': user.nickname, 'id': user.id, 'time_sent': time_sent, 'img': img}, room=room_id)  # Newly added 'time_sent' field to the output
    else:
        print("Error sending message")

#########################################################
@views.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('views.dashboard'))
    else:
        return render_template('index.html', user=current_user)
    
@views.route('/dashboard')
@login_required
def dashboard():
    public_rooms = get_public_rooms()
    my_rooms = current_user.rooms
    return render_template('dashboard.html', user=current_user, rooms=get_rooms_count(), public_rooms=public_rooms, my_rooms=my_rooms)

@views.route('/games')
def games():
    return render_template('games.html', user=current_user)

@views.route('/games/snake')
def games_snake():
    return render_template('/games/snake.html', user=current_user)

@views.route('/create', methods=['GET', 'POST'])
@login_required
def create_room_route():
    room_id, invite_code = None, None
    if current_user.is_authenticated:
        try:
            if request.method == 'POST':
                # Process form submission and create the room
                room_name = request.form.get('room_name')
                room_type = request.form.get('room_type')
                room_keywords = request.form.get('room_keywords')
                room_name = bleach.clean(room_name)
                room_keywords = bleach.clean(room_keywords)
                if room_type == 'is_private':
                    is_private = True
                else:
                    is_private = False
                # Create room and get the room ID and invite code
                room_id, invite_code = create_room(room_name=room_name, is_private=is_private, admin_id=current_user.id, description=room_keywords)
                flash(f'🎉 Room <strong>{room_name}</strong> created successfully! <strong>Code: {invite_code}</strong>', category='success')
                # Redirect with parameters directly in the URL
                return redirect(url_for('views.join_room_route', room_id=room_id))
            # This return statement was missing
            return render_template('create.html', room_id=room_id, invite_code=invite_code, user=current_user)
        except Exception as e:
            print("OHH NOOO --!!!--:", e)
            
@views.route('/join_room/<string:room_id>', methods=['GET', 'POST'])
@login_required
def join_room_route(room_id):
    invite_code = request.args.get('invite_code')
    room = Room.query.get(room_id)
    if room.is_private:
        flash('Room is private. You need to join via invite code or link!', category='error')
        return redirect(url_for('views.dashboard'))
    elif room:
        # Check if the user is already associated with the room
        if current_user in room.users:
            return redirect(url_for('views.chat', room_id=room_id))
        else:
            room.users.append(current_user)
            db.session.commit()
            return redirect(url_for('views.chat', room_id=room_id))
    else:
        flash('Room not found.', category='error')
    return redirect(url_for('views.dashboard'))

@views.route('/leave_room/<string:room_id>', methods=['GET', 'POST'])
@login_required
def leave_room_route(room_id):
    room = Room.query.get(room_id)
    if current_user in room.users:
        room.users.remove(current_user)
        db.session.commit()
        flash(f'You have left the room: {room.room_name}', category='success')
    else:
        flash(f'You are not in the room: {room.room_name}', category='warning')
    return redirect(url_for('views.dashboard'))

@views.route('/edit/<string:room_id>', methods=['GET', 'POST'])
@login_required
def edit_room(room_id):
    room = Room.query.get(room_id)
    
    if current_user in room.admins or current_user.id == room.admin_id:
        if request.method == 'POST':
            if 'save_changes' in request.form:
                # Update room details based on form data
                room.room_name = request.form.get('room_name')
                room.is_private = 'is_private' in request.form
                room.description = request.form.get('description')
                room.invite_code = request.form.get('generate_code')     
                db.session.commit()
                flash("Room details updated successfully!", category="success")
                return redirect(url_for('views.edit_room', room_id=room_id))
            elif 'add_admin' in request.form:
                new_admin_ids = request.form.getlist('new_admin_ids')
                add_admins(room, new_admin_ids)
                flash("Admins added!", category="success")
                db.session.commit()
            elif 'remove_admin' in request.form:
                admin_id_to_remove = request.form.get('admin_id_to_remove')
                remove_admin(room, admin_id_to_remove)
                flash("Admins removed!", category="success")
                db.session.commit()
            return redirect(url_for('views.edit_room', room_id=room_id))
        return render_template('edit_room.html', user=current_user, room=room, admins=get_admins(room))
    else:
        flash("No access!", category="error")
        return redirect(url_for('views.edit_room', room_id=room_id))

@views.route('/chat/<string:room_id>', methods=['GET', 'POST'])
@login_required
def chat(room_id):
    room = Room.query.get(room_id)
    if current_user in room.users:
        # Fetch message history from the database
        message_history = Message.query.filter_by(room_id=room.id).order_by(Message.timestamp).all()
        users = room.users
        # Handle user search
        search_term = request.args.get('search', '').lower()
        if search_term:
            users = [user for user in users if search_term in user.nickname.lower()]
        return render_template('chat.html', user=current_user, room=room, message_history=message_history, users=users, search_term=search_term, smileys=smiley_list())
    else:
        flash(f'You have not joined this room!', category='error')
        return redirect(url_for('views.index'))

@views.route('/join', methods=['GET', 'POST'])
@login_required
def join():
    if request.method == 'POST':
        invite_code = request.form.get('invite_code')
        room = Room.query.filter_by(invite_code=invite_code).first()
        if room:
            # Add the user to the room
            room.users.append(current_user)
            db.session.commit()
            flash(f'Successfully joined room: {room.room_name}', 'success')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='dash.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='chat.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='settings.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.3/purify.min.js"></script>
    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js" integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3a95edba20.js" crossorigin="anonymous"></script>
    <meta http-equiv="Content-Security-Policy" content="
        default-src 'self';
        font-src 'self' https://ka-f.fontawesome.com;
        script-src 'self' https://cdnjs.cloudflare.com https://cdn.socket.io https://code.jquery.com https://cdn.jsdelivr.net https://stackpath.bootstrapcdn.com 'unsafe-inline';
        style-src 'self' https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net 'unsafe-inline';
        img-src 'self' https://i.ibb.co/ https://media.giphy.com/ https://*.giphy.com/ https://*.imgbb.com/ https://*.imgur.com https://*.unsplash.com https://*.pixabay.com;">
        
    <title>{% block title %}The Chat{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse ml-auto" id="navbar">
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" id="home" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" id="login" href="/login">Login</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" id="dashboard" href="/dashboard">Dash</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="roomsDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Rooms
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="roomsDropdown">
                            <a class="dropdown-item" href="/create">Create</a>
                            <a class="dropdown-item" href="/join">Join</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle username-field" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="/settings">Settings</a>
                            <a class="dropdown-item" href="/logout">Log Out</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% with alert = get_flashed_messages(with_categories=true) %}
    {% if alert %}
        {% for category, message in alert%}
        {% if category=="error" %}
            <div style="margin: 0; z-index: 1;" class="alert alert-danger alter-dismissable fade show">
                {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% else %}
            <div style="margin: 0; z-index: 1;" class="alert alert-success alter-dismissable fade show">
                {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script
        src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

website/templates/chat.html
{% extends "base.html" %}
{% block title %}WhisperTalk | {{room.room_name}} {% endblock %}
{% block content %}

<div class="chat-body">
    <div class="chat-header">
        <div>
            <button id="user-menu" onclick="toggleAndCloseUserList()"><i class="fa-solid fa-users"></i></button>
            <label id="roomname">{{ room.room_name }}</label>
        </div>
        <div>
            <a style="text-decoration:none;" href="{{ url_for('views.view_profile', user_id=current_user.id) }}"><img id="head-usr" src="{% if current_user.img %}{{ current_user.img }}{% else %}{{ "https://cdn.pixabay.com/photo/2018/11/13/21/43/avatar-3814049_1280.png" | string }}{% endif %}" alt="Profile Image" style="width: 40px; height: 40px; border: 1.5px solid rgba(0, 128, 128, 0.9); border-radius: 50%; margin-right: 10px;"></a>
            <label id="username">{{ current_user.nickname }}</label>
        </div>
    </div>
    <div class="chat" id="chat" room-id="{{ room.id }}">
        <ul id="chat-messages">
            {% for message in message_history %}
            <li class="{% if message.user == current_user %}current-user{% else %}other-user{% endif %}">
                <div class="user-profile">
                    <a style="text-decoration:none;" href="{{ url_for('views.view_profile', user_id=message.user.id) }}"><img src="{% if message.user.img %}{{ message.user.img }}{% else %}https://cdn.pixabay.com/photo/2018/11/13/21/43/avatar-3814049_1280.png{% endif %}" alt="Profile Image"></a>
                </div>
                <div class="message-content">
                    <span id="username" style="font-size: small; font-weight: bold;"><a style="text-decoration:none; color:white;" href="{{ url_for('views.view_profile', user_id=message.user.id) }}">{{ message.user.nickname }}</a> </span>
                    {% if message.data.startswith('`') and message.data.endswith('`') %}
                    {% set content = message.data[1:-1] %}
                        <span style="font-size: small; word-break: break-all;" id="message-embed">{{ content | safe }}</span>
                    {% else %}
                        <span style="font-size: small; word-break: break-all;">{{ message.data | safe }}</span>
                    {% endif %}
                </div>
                <span class="timestamp">{{ message.timestamp.strftime("%H:%M") }}</span>
            </li>
            {% endfor %}
            <!-- New messages displayed here -->
        </ul>
    </div>
    <div class="chat-input">
        <textarea id="message" placeholder="Enter a message..." maxlength="2500" oninput="updateCharacterCount(this)" onkeydown="keyCheck(event)" rows="2"></textarea>
        <span style="font-size:10px;" id="charCount">2500</span>
        <button id="btn-send" onclick="sendMessage()"><i class="fa-solid fa-paper-plane"></i></button>
        <button id="btn-smiley" onclick="toggleSmileyMenu()"><i class="fa-solid fa-face-smile"></i></button>
        <button id="btn-smiley" onclick="toggleGifMenu()"><i class="fa-solid fa-bolt"></i></button>
        <button id="btn-smiley" onclick="openImageAttach()"><i class="fa-solid fa-image"></i></button>
        <div id="smiley-menu">
            {% for smiley in smileys %}
                <button onclick="addSmiley('{{ smiley }}')">{{ smiley | safe }}</button>
            {% endfor %}
        </div>
        <div id="giphy-menu">
            <input style="margin-bottom: 10px; margin-top: 10px;" type="text" id="giphy-search" placeholder="Search GIFs...">
            <button style="color:white; font-size:15px; width:10%;" id="btn-search" onclick="searchGifs()"><i class="fa-solid fa-magnifying-glass"></i></button>
            <div id="giphy-results"></div>
        </div>
        <input type="file" id="image-input" style="display: none;" accept="image/*" onchange="handleImageInput(this)">
    </div>
</div>

<!-- User List Section -->
<div id="user-list">
    <span class="close-btn" onclick=" toggleAndCloseUserList()">&times;</span>
    <h2>{{ "Room" }} {{ "Users" }}</h2>
    <!-- User Search -->
    <form style="text-align:center;  margin-bottom:10px;" action="{{ url_for('views.chat', room_id=room.id) }}" method="get">
        <input style="background-color:#1f2127; border-radius:5px;" type="text" id="user-search" name="search" placeholder="Search users..." value="{{ search_term }}" oninput="filterUserList()">
    </form>
    <!-- Display Users -->
    <ul>
        {% for user in room.users %}
            <li>
                <div class="user-options">
                    <a href="{{ url_for('views.view_profile', user_id=user.id) }}" class="user-option">{{ user.nickname }}</a>
                    <button class="user-option" onclick="" href="_blank">Send DM</button>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
<script type="text/javascript" src="{{ url_for('static', filename='chat.js') }}"></script>
<script>
    window.onload = function() {
        var chatContainer = document.getElementById("chat");
        chatContainer.scrollTop = chatContainer.scrollHeight;
    };
</script>
{% endblock %}

website/templates/create.html
{% extends "base.html" %}

{% block title %}WhisperTalk | Create Room{% endblock %}

{% block content %}
<style>
    /* Create Room Page Styles */
    .create_room {
        max-width: 400px;
        margin: auto;
        margin-top: 10%;
        padding: 20px;
        border: 1px solid rgba(0, 128, 128, 0.6);
        border-radius: 8px;
        background-color: #1f2127; /* Matched color */
        box-shadow: 0 0 20px rgba(0, 128, 128, 0.8), 0 0 40px rgba(0, 128, 128, 0.5), 0 0 80px rgba(0, 128, 128, 0.3);
    }
    
    .create_room h3 {
        text-align: center;
        color: #61dafb; /* Matched color */
        margin-bottom: 20px;
    }
    
    .form-group {
        margin-bottom: 20px;
    }
    
    .input-control, textarea {
        width: 100%;
        padding: 10px;
        border: 2px solid rgba(0, 128, 128, 0.9); /* Matched color */
        outline:none;
        border-radius: 10px;
        margin-bottom: 15px;
        background-color: #1f2127; /* Matched color */
        color: #61dafb; /* Matched color */
    }
    
    .form-switch {
        margin-bottom: 20px;
        color:#61dafb;
    }
    
</style>

<div class="create_room">
    <h3>Create Room</h3>
    <form method="post" action="{{ url_for('views.create_room_route') }}">
        <div class="form-group">
            <label style="color:#61dafb;" for="room_name">Room Name</label>
            <input type="text" id="room_name" placeholder="25 characters max..." name="room_name" class="input-control" maxlength="25" oninput="updateCharacterCount(this)" required>
        </div>
        <!-- Use Bootstrap form-switch for private/public selection -->
        <div class="form-switch">
            <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="is_private" name="is_private">
                <label class="custom-control-label" for="is_private">Private Room</label>
            </div>
        </div>
        <div class="form-group">
            <label style="color:#61dafb;" for="room_keywords">Description</label>
            <textarea style="resize: none;" placeholder="Enter room description..." type="text" id="room_keywords" name="room_keywords" class="input-control" maxlength="100" oninput="updateCharacterCount(this)" onkeydown="keyCheck(event)" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn-primary">Create</button>
    </form>
</div>

{% endblock %}

website/templates/dashboard.html
{% extends "base.html" %}
{% block title %}WhisperTalk | Dash{% endblock %}
{% block content %}
    <div class="dash-container">
        <div class="dash-tabs-container">
            <div class="dash-tab" onclick="toggleTab('myDm')"  data-tab-id="myDm"><i class="fa-solid fa-envelope"></i></div>
            <div class="dash-tab active" onclick="toggleTab('myRooms')"  data-tab-id="myRooms"><i class="fa-solid fa-house"></i></div>
            <div class="dash-tab" onclick="toggleTab('publicRooms')" data-tab-id="publicRooms"><i class="fa-solid fa-people-roof"></i></div>
        </div>

        <div id="myDm" class="dash-tab-content" style="display: none;">
            <h2>Direct Messages</h2>
            <ul class="dash-rooms-list">
                {% for dm in direct_messages %}
                    <li class="dash-room-item">
                        <div class="dash-room-details">
                            <div class="dash-room-description">
                                <span class="dash-room-name">{{ dm.other_user.nickname }}</span>
                                <!-- Add other details specific to direct messages -->
                            </div>
                        </div>
                        <div class="dash-room-users"><i class="fa-solid fa-user"></i> <span>1</span></div>
                        <div id="dash-buttons">
                            <a href="{{ url_for('views.dm_chat', user_id=dm.other_user.id) }}"><button class="btn-secondary" id="chat-button"><i class="fa-solid fa-message"></i> CHAT</button></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div id="myRooms" class="dash-tab-content">
            <h2>My Rooms</h2>
            <ul class="dash-rooms-list">
                {% for room in my_rooms %}
                    <li class="dash-room-item">
                        <div class="dash-room-details">
                            <div class="dash-room-description">
                                <span class="dash-room-name">{{ room.room_name }}</span>
                                <details id="quickview">
                                    <summary>Description</summary>
                                    <i class="fa-solid fa-clipboard"></i>
                                    <span style="border-radius:5px; padding:3px; auto;background-color:#363b49; word-break: break-word;"> {{ room.description }}</span>
                                </details>
                            </div>
                        </div>
                        <div class="dash-room-users"><i class="fa-solid fa-user-group"></i> <span>{{ room.users|length }}</span></div>
                        <div id="dash-buttons">
                            {% if current_user in room.admins or current_user.id == room.admin_id %}
                                <a href="{{ url_for('views.edit_room', room_id=room.id) }}"><button class="btn-secondary" id="edit-button"><i class="fa-solid fa-pen-to-square"></i> EDIT</button></a>
                            {% endif %}
                            <a href="{{ url_for('views.chat', room_id=room.id) }}"><button class="btn-secondary" id="chat-button"><i class="fa-solid fa-message"></i> CHAT</button></a>
                            <a href="{{ url_for('views.leave_room_route', room_id=room.id) }}"><button class="btn-secondary" id="leave-button"><i class="fa-solid fa-door-open"></i> LEAVE</button></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div id="publicRooms" class="dash-tab-content" style="display: none;">
            <h2>Public Rooms</h2>
            <ul class="dash-rooms-list">
                {% for room in public_rooms %}
                <li class="dash-room-item">
                    <div class="dash-room-details">
                        <div class="dash-room-description">
                            <span class="dash-room-name">{{ room.room_name }}</span>
                            <details id="quickview">
                                <summary>Description</summary>
                                <i class="fa-solid fa-clipboard"></i>
                                <span style="border-radius:5px; padding:3px; background-color:#363b49;">{{ room.description }}</span>
                            </details>
                        </div>
                    </div>
                    <div class="dash-room-users"><i class="fa-solid fa-user-group"></i> <span>{{ room.users|length }}</span></div>
                    <div id="dash-buttons">
                        <a href="{{ url_for('views.join_room_route', room_id=room.id) }}"><button class="btn-secondary" id="chat-button"><i class="fa-solid fa-right-to-bracket"></i> JOIN</button></a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <script>
        function toggleTab(tabId) {
            document.querySelectorAll('.dash-tab-content').forEach(tabContent => {
                tabContent.style.display = 'none';
            });
            document.querySelectorAll('.dash-tab').forEach(tab => {
                tab.classList.remove('active');
            });
            document.getElementById(tabId).style.display = 'block';
            document.querySelector(`.dash-tab[data-tab-id="${tabId}"]`).classList.add('active');
        }
    </script>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block title %}WhisperTalk Home{% endblock %}

{% block content %}
<h1>HOMEPAGE</h1>
{% endblock %}

website/templates/join.html
{% extends "base.html" %}

{% block title %}WhisperTalk | Join Room{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
    <!-- Add Bootstrap CSS link here if not already included -->
{% endblock %}

{% block content %}
<style>
    .join_room {
        max-width: 400px;
        margin: auto;
        margin-top: 10%;
        padding: 50px;
        border: 1px solid rgba(0, 128, 128, 0.6);
        border-radius: 8px;
        background-color: #1f2127;
        box-shadow: 0 0 20px rgba(0, 128, 128, 0.8), 0 0 40px rgba(0, 128, 128, 0.5), 0 0 80px rgba(0, 128, 128, 0.3);
        color:#61dafb;
    }
    
    .join_room h3 {
        text-align: center;
        color: #333;
        margin-bottom: 20px;
        color:#61dafb;
    }
    
    .form-group {
        margin-bottom: 20px;
    }
    
    .input-control {
        width: 100%;
        padding: 10px;
        border: 2px solid #ccc;
        border-radius: 10px;
        margin-bottom: 15px;
        border: 2px solid rgba(0, 128, 128, 0.9); /* Matched color */
        background-color: #1f2127; /* Matched color */
        color: #61dafb; /* Matched color */
        outline:none;
    }
</style>

<div class="join_room">
    <h3>Join Room</h3>
    <form method="post" action="{{ url_for('views.join') }}">
        <div class="form-group">
            <label for="invite_code">Enter 10-digit Invite Code</label>
            <input type="text" id="invite_code" name="invite_code" class="input-control" title="Please enter a 10-digit invite code" required>
        </div>
        <button type="submit" class="btn-primary">Join Room</button>
    </form>
</div>

{% endblock %}